---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi

- name: download docker key
  command: >
    gpg --keyserver p80.pool.sks-keyservers.net
    --recv 58118E89F3A912897C070ADBF76221572C52609D
  register: docker_key_result
  changed_when: "'unchanged: 1' not in docker_key_result.stderr"
  sudo: yes

- name: write docker key to /root
  command: >
    gpg --output /root/docker.gpg
        --export 58118E89F3A912897C070ADBF76221572C52609D
  args:
    creates: /root/docker.gpg
  sudo: yes

- name: add docker key to apt-key
  apt_key: file=/root/docker.gpg
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- name: install https apt transport and certificates
  apt: name={{ item }}
  with_items:
  - apt-transport-https
  - ca-certificates
  sudo: yes

- name: docker sources.list
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

- name: Remove lxc-docker if exists
  apt: name=lxc-docker state=absent
  sudo: yes

- name: Install docker
  apt: name=docker-engine
  sudo: yes

- name: add docker group to users
  user: name={{ item }} groups=docker append=yes
  with_items: '{{docker_users}}'
  sudo: yes
